### PR TITLE
 added automation of wodle configs for aws logs to cf template

### PR DESCRIPTION
**Pull request by sonofagl1tch**
Issue #5

*Description of changes:*

added automation of wodle configs for aws logs to cf template

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mgmacias95** [comment]
Hi @sonofagl1tch,

I don't understand this: do you want to merge commits **from** master into branch `automate-ingest-AWS-logs-into-wazuh`? Which changes does this PR add? I think these changes are already made in #16.
imagen

Best regards,
Marta

**Comment by sonofagl1tch** [comment]
#16 only changed 1 file but #18 changed 5 files

**Comment by mgmacias95** [comment]
Hi @sonofagl1tch,

Isn't that already added in commit https://github.com/sonofagl1tch/AWSDetonationLab/commit/7db2abc09fd9a7201483748ef9bb08744aa7e77b? Both #16 and #18 are pull requests FROM master branch TO a development branch. Which means, changes are already present in master branch.

Best regards,
Marta

**Comment by sonofagl1tch** [comment]
Closing this PR as sonofagl1tch created it backwards since he is a noob at git.

**Pull request closed without merging**
