### PR TITLE
Add support for virus total wazuh integration

### LINKED ISSUE #4: add VirusTotal integration to wazuh in detonation lab
update cloudformation template to prompt for a VT key during the build stage that will configure the wazuh server to use their VT integration.

https://documentation.wazuh.com/3.x/user-manual/capabilities/virustotal-scan/index.html

### PR DESCRIPTION
**Pull request by mgmacias95**
*Issue #, if available:*
closes #4 

*Description of changes:*
A virus total parameter has been added to the template:
* if it's None, nothing happens
* otherwise, a virus total integration is configured at Wazuh.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mgmacias95** [comment]
I have added custom rules to silent the following alerts from wazuh:
* `VirusTotal: Alert - No records in VirusTotal database`
* `VirusTotal: Alert - $(virustotal.source.file) - No positives found`

Those two alerts made the integration very noisy and I don't consider them quite important.

**Review by sonofagl1tch — CHANGES_REQUESTED** [review]
Can you add configurations for the file integrity check and VT checks to cover /home/ recursively on linux and for windows: desktop, documents, downloads, c:\, startup programs, and userdata directories

**Comment by mgmacias95** [comment]
This is ready to review @sonofagl1tch 😄 !

**Review by sonofagl1tch — CHANGES_REQUESTED** [review]
unable to reproduce success of a binary hash check against virustotal. I ran the template and waited 10 minutes after it finished to SCP malware to the linuxVictim under the ec2-user home directory. I then checked Wazuh for any events with the hashes. Then I copied the malware files to /bin as that is one of the well known monitored directories of the wazuh agent configuration. Still no events in wazuh for the hashes. We should review my deployment of the new template and scripts to verify if all of the expected changes are present. Based on my observations so far, all of the expected changes exist.

**Comment by mgmacias95** [comment]
Hello @sonofagl1tch,

I merged changes from #62 in this branch. Can you try redeploying it again? I think this can fix your issue.

Best regards,
Marta

**Review by sonofagl1tch — APPROVED** [review]

**Pull request merged**
